#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,16.9,0
#
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/tcpEcho_pem3.oem3.dep
package/cfg/tcpEcho_pem3.oem3.dep: ;
endif

package/cfg/tcpEcho_pem3.oem3: | .interfaces
package/cfg/tcpEcho_pem3.oem3: package/cfg/tcpEcho_pem3.c package/cfg/tcpEcho_pem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -mv7M3 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/rtu" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/ndk_2_25_00_09/packages/ti/ndk/inc/bsd" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/tcp" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/include" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/port" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/MWare_v202a" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/bios_6_45_01_29/packages/ti/sysbios/posix" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --define=ccs --define=MWARE -g --gcc --diag_warning=225 --diag_warning=255 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --ual   -qq -pdsw225 -ms --fp_mode=strict --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3   -Dxdc_cfg__xheader__='"xconfig_tcpEcho/package/cfg/tcpEcho_pem3.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s oem3 $< -C   -mv7M3 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/rtu" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/ndk_2_25_00_09/packages/ti/ndk/inc/bsd" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/tcp" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/include" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/port" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/MWare_v202a" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/bios_6_45_01_29/packages/ti/sysbios/posix" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --define=ccs --define=MWARE -g --gcc --diag_warning=225 --diag_warning=255 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --ual   -qq -pdsw225 -ms --fp_mode=strict --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3   -Dxdc_cfg__xheader__='"xconfig_tcpEcho/package/cfg/tcpEcho_pem3.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/tcpEcho_pem3.oem3: export C_DIR=
package/cfg/tcpEcho_pem3.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/;$(PATH)
package/cfg/tcpEcho_pem3.oem3: Path:=$(ti.targets.arm.elf.M3.rootDir)/bin/;$(PATH)

package/cfg/tcpEcho_pem3.sem3: | .interfaces
package/cfg/tcpEcho_pem3.sem3: package/cfg/tcpEcho_pem3.c package/cfg/tcpEcho_pem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -mv7M3 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/rtu" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/ndk_2_25_00_09/packages/ti/ndk/inc/bsd" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/tcp" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/include" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/port" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/MWare_v202a" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/bios_6_45_01_29/packages/ti/sysbios/posix" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --define=ccs --define=MWARE -g --gcc --diag_warning=225 --diag_warning=255 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --ual   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3   -Dxdc_cfg__xheader__='"xconfig_tcpEcho/package/cfg/tcpEcho_pem3.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/cfg -fr=./package/cfg -fc $<
	$(MKDEP) -a $@.dep -p package/cfg -s oem3 $< -C  -n -s --symdebug:none -mv7M3 --code_state=16 --float_support=vfplib -me --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/rtu" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/ndk_2_25_00_09/packages/ti/ndk/inc/bsd" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/tcp" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus/include" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/modbus" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3/port" --include_path="C:/Users/Volkodav/workspace_v6_2/MITU_M3" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/MWare_v202a" --include_path="C:/ti/tirtos_c2000_2_16_00_08/products/bios_6_45_01_29/packages/ti/sysbios/posix" --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_16.9.0.LTS/include" --define=ccs --define=MWARE -g --gcc --diag_warning=225 --diag_warning=255 --diag_wrap=off --display_error_number --gen_func_subsections=on --abi=eabi --ual   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3   -Dxdc_cfg__xheader__='"xconfig_tcpEcho/package/cfg/tcpEcho_pem3.h"'  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_16_9_0 -O2  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/cfg -fr=./package/cfg
	-@$(FIXDEP) $@.dep $@.dep
	
package/cfg/tcpEcho_pem3.sem3: export C_DIR=
package/cfg/tcpEcho_pem3.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/;$(PATH)
package/cfg/tcpEcho_pem3.sem3: Path:=$(ti.targets.arm.elf.M3.rootDir)/bin/;$(PATH)

clean,em3 ::
	-$(RM) package/cfg/tcpEcho_pem3.oem3
	-$(RM) package/cfg/tcpEcho_pem3.sem3

tcpEcho.pem3: package/cfg/tcpEcho_pem3.oem3 package/cfg/tcpEcho_pem3.mak

clean::
	-$(RM) package/cfg/tcpEcho_pem3.mak
