/*
 * ERROR_NUMBERS.h
 *
 *  Created on: 12.12.2014
 *      Author: VKD
 */

#ifndef ERROR_NUMBERS_H_
#define ERROR_NUMBERS_H_

#define SYSTEM_STATE_UNDEFINED 0
#define SYSTEM_STATE_INIT 1
#define SYSTEM_STATE_IDLE_DISCHARGED 2
#define SYSTEM_STATE_IDLE_CHARGED 3
#define SYSTEM_STATE_EXCITATION 4
#define SYSTEM_STATE_READYTOSYNC 5
#define SYSTEM_STATE_DCLOAD 6
#define SYSTEM_STATE_SYNC 7
#define SYSTEM_STATE_OPERATION_NORMAL 8
#define SYSTEM_STATE_OPERATION_WARNING 9
#define SYSTEM_STATE_EMERGENCY 10
#define SYSTEM_STATE_STOPPING 11

#define ERR_UNEXPECTED 0
#define ERR_EMERGENCY_STOP_ALG 1
#define ERR_CPU_OVERLOAD 2
#define ERR_MAIN_IRQ_LOSS 3
#define ERR_ADC_IRQ_LOSS 4
#define ERR_DMA_OVERRIDE 5

#define ERR_CONVERTER_COOLING_FAULT 6
#define ERR_GROUND_FAULT_PROTECTION 7
#define ERR_ACTIVE_POWER_REGULATION 8
#define ERR_SHORT_SYNC_STOPPED 9

#define ERR_CHOPPER_OVERCURRENT 10
#define ERR_EXCITATION_OVERCURRENT 11
#define ERR_DCIN_OVERVOLTAGE 12
#define ERR_DCOUT_OVERVOLTAGE 13
#define ERR_PHA_OVERTEMP 14
#define ERR_PHB_OVERTEMP 15
#define ERR_PHC_OVERTEMP 16
#define ERR_CHOPPER_OVERTEMP 17
#define ERR_GENPHASE_OVERVOLTAGE 18
#define ERR_OUTPUTPHA_OVERCURRENT 19
#define ERR_OUTPUTPHB_OVERCURRENT 20
#define ERR_OUTPUTPHC_OVERCURRENT 21
#define ERR_OUTPUTPHA_OVERVOLTAGE 22
#define ERR_OUTPUTPHB_OVERVOLTAGE 23
#define ERR_OUTPUTPHC_OVERVOLTAGE 24
#define ERR_OUTPUT_OVERLOAD 25
#define ERR_OUTPUT_NEGATIVE_POWER 26
#define ERR_OUTPUT_REACTIVE_OVERLOAD 27
#define ERR_DCIN_OPERATION_UNDERVOLTAGE 28
#define ERR_DCOUT_OPERATION_UNDERVOLTAGE 29
#define ERR_IGBT_TEMP_UNBALANCE 30
#define ERR_GENSPEED_OPERATION_OVERRANGE 31

#define ERR_RMSPHA_OVERVOLTAGE 32
#define ERR_RMSPHB_OVERVOLTAGE 33
#define ERR_RMSPHC_OVERVOLTAGE 34
#define ERR_RMSPHA_OVERCURRENT 35
#define ERR_RMSPHB_OVERCURRENT 36
#define ERR_RMSPHC_OVERCURRENT 37
#define ERR_MEANPHA_OVERTEMP 38
#define ERR_MEANPHB_OVERTEMP 39
#define ERR_MEANPHC_OVERTEMP 40
#define ERR_RMSINVPHA_OVERCURRENT 41
#define ERR_RMSINVPHB_OVERCURRENT 42
#define ERR_RMSINVPHC_OVERCURRENT 43
#define ERR_MEANIDC1_OVERCURRENT 44
#define ERR_MEANIDC2_OVERCURRENT 45
#define ERR_MEANCHOPP_OVERTEMP 46
#define ERR_MEANIEXC_OVERCURRENT 47
#define ERR_MEANUDCOUT_OVERVOLTAGE 48
#define ERR_MEANUDCIN_OVERVOLTAGE 49
#define ERR_RMSUGEN_OVERVOLTAGE 50

#define ERR_MEANRECT1_OVERCURRENT 51
#define ERR_MEANRECT2_OVERCURRENT 52
#define ERR_MEANRECT3_OVERCURRENT 53

#define ERR_RMSIGEN_OVERCURRENT 54

#define ERR_OUTPUT_FREQENCY_OVERRANGE 55
#define ERR_VOLTAGE_UNBALANCE 56
#define ERR_RECTCURRENT_UNBALANCE 57
#define ERR_CURRENT_UNBALANCE 58
#define ERR_IGBT_CURRENT_UNBALANCE 59
#define ERR_UGEN_OPERATION_UNDERVOLTAGE 60
#define ERR_UGEN_DCOUT_CORRELATION 61
#define ERR_IGEN_IRECT_CORRELATION 62
#define ERR_OUTPUT_FREQ_OVERRANGE 63


#define ERR_FPGA_FLAGS_PROTECTIONS 64

#endif /* ERROR_NUMBERS_H_ */
